import json
import sys

from model_tuner.sim_manager import SimBatchPaths


'''
def get_batch_params():
    """Generate params for batchtools to probe. """

    # Take the base folder path from the 1-st cmdline arg,
    # with which SimManager called the master batch script
    dirpath_base = sys.argv[1]

    # Collection of hpc paths used by SimManagerHPCBatch
    paths = SimBatchPaths.create_default(dirpath_base)

    # Read sim labels from the requests json file
    with open(paths.requests_file, 'r') as fid:
        requests = json.load(fid)
    sim_labels = list(requests.keys())

    batch_params = {
        'sim_manager.sim_label': sim_labels,
        'sim_manager.requests_file': [paths.requests_file],
    }

    print('Batch params:', flush=True)
    print(batch_params, flush=True)

    return batch_params
'''

def post_update(cfg):
    """Called after cfg.update() """
    
    dirpath_res = cfg.saveFolder
    sim_label = cfg.sim_manager['sim_label']
    fpath_reqs = cfg.sim_manager['requests_file']

    print(f'Job script started (label={sim_label})', flush=True)
    print(f'File with sim requests: {fpath_reqs}', flush=True)
    print(f'Output folder for the results: {dirpath_res}', flush=True)

    # Set the sim label that was passed from SimManager
    cfg.simLabel = sim_label

    # Read the request generated by SimManager
    with open(fpath_reqs, 'r') as fid:
        sim_request = json.load(fid)[sim_label]

    print('Request:')
    print(sim_request)

    # Get cfg fields from the request
    if 'input' in sim_request:
        cfg.ou_pop_inputs = sim_request['input']
    if 'connected' in sim_request:
        cfg.addConn = sim_request['connected']
    if 'wmult' in sim_request:
        cfg.wmult = sim_request['wmult']
    if 'subnet_params' in sim_request:
        cfg.subnet_params |= sim_request['subnet_params']
    #if 'duration' in sim_request:
    #    cfg.duration = sim_request['duration']
