command_template = "sbatch {output_path}.sh"

script_template = """\
#!/bin/bash
#SBATCH --job-name={label}
#SBATCH -A TG-MED240050
#SBATCH -t 5:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=45
#SBATCH --mem=4G
#SBATCH --partition=compute

{handles}
{env}

source ~/.bashrc
conda activate fitune
module load openmpi/mlnx/gcc/64/4.1.5a1
cd {project_dir}
{command} > {stdout} 2>&1
"""
