"""
Low-level functions to extract data from a NetPyNE simulation result.

"""

import os
from typing import Dict, List, Tuple

import numpy as np
import xarray as xr


def get_pop_names(sim_result):
    return list(sim_result['net']['pops'].keys())

def get_lfp_coords(sim_result):
    cfg = sim_result['simConfig']
    lfp_coords = np.array(cfg['recordLFP'])
    return lfp_coords

def get_record_times(sim_result):
    cfg = sim_result['simConfig']
    dt = cfg['recordStep']
    T = cfg['duration']
    tt = np.arange(0, T, dt)
    return tt

def get_lfp(sim_result):
    lfp = np.array(sim_result['simData']['LFP']).T
    lfp_coords = get_lfp_coords(sim_result)
    tt = get_record_times(sim_result)
    return lfp, tt, lfp_coords

def get_pop_lfps(sim_result):
    lfp = {}
    for pop_name, pop_lfp in sim_result['simData']['LFPPops'].items():
        lfp[pop_name] = np.array(pop_lfp).T
    lfp_coords = get_lfp_coords(sim_result)
    tt = get_record_times(sim_result)
    return lfp, tt, lfp_coords

def get_pop_ylim(sim_res, pop_name):
    h = sim_res['simConfig']['sizeY']
    yy = sim_res['net']['pops'][pop_name]['tags']['ynormRange']
    return (yy[0] * h, yy[1] * h)

def get_layer_borders(sim_result):
    layer_yrange = {}
    for pop_name in sim_result['net']['pops']:
        layer_yrange[pop_name] = get_pop_ylim(sim_result, pop_name)
    return layer_yrange

def get_net_params(sim_result):
    return sim_result['net']['params']

def get_pop_params(sim_result, pop_name=None):
    if pop_name is None:
        return get_net_params(sim_result)['popParams']
    else:
        return get_net_params(sim_result)['popParams'][pop_name]

def get_pop_cell_gids(sim_result, pop_name):
    return sim_result['net']['pops'][pop_name]['cellGids']

def get_sim_data(sim_result):
    return sim_result['simData']

def get_pop_size(sim_result, pop_name) -> int:
    return len(get_pop_cell_gids(sim_result, pop_name))

def get_net_size(sim_result) -> Dict[str, int]:
    return {pop_name: get_pop_size(sim_result, pop_name)
            for pop_name in get_pop_names(sim_result)}

def get_sim_duration(sim_result):
    return sim_result['simConfig']['duration'] / 1000

def get_pop_spikes(sim_result, pop_name, combine_cells=True,
                   t0=0, tmax=None, subtract_t0=True, ms=False,
                   ndigits=6) -> List[np.ndarray]:
    """Get times of spikes generated by a given population. """
    sim_data = get_sim_data(sim_result)
    pop_cell_idx = get_pop_cell_gids(sim_result, pop_name)
    spike_cell_idx = np.array(sim_data['spkid'])
    spkt = np.array(sim_data['spkt']) / 1000
    tmax = tmax or get_sim_duration(sim_result)
    t_mask = (spkt >= t0) & (spkt <= tmax)
    tsub = t0 if subtract_t0 else 0
    mult = 1000 if ms else 1
    if combine_cells:
        pop_mask = np.isin(sim_data['spkid'], pop_cell_idx)
        spike_times = (spkt[pop_mask & t_mask] - tsub) * mult
        spike_times = [np.round(spike_times, ndigits)]
    else:
        spike_times = []
        for cell_id in pop_cell_idx:
            cell_mask = (spike_cell_idx == cell_id)
            s = (spkt[cell_mask & t_mask] - tsub) * mult
            s = np.round(s, ndigits)
            spike_times.append(s)
    return spike_times

def get_net_spikes(sim_result, pop_names=None, combine_cells=True,
                   t0=0, tmax=None, subtract_t0=True, ms=False,
                   ndigits=6) -> Dict[str, List[np.ndarray]]:
    """Get times of spikes generated by a given set of populations. """
    pop_names = pop_names or get_pop_names(sim_result)
    S = {}
    for pop_name in pop_names:
        S[pop_name] = get_pop_spikes(
            sim_result, pop_name, combine_cells, t0, tmax,
            subtract_t0, ms, ndigits=6
        )
    return S

'''def get_voltages(
        sim_result: Dict,
        t_limits: Tuple[float, float] | None = None,
        ) -> Tuple[Dict[str, np.ndarray], np.ndarray]:
    """Returns (V_data, tvec), where V_data is a dict: {pop: Vmat (cells x time)}. """

    pop_names = get_pop_names(sim_result)

    # Time bins and limits
    tvec = np.array(sim_result['simData']['t'])
    if t_limits is not None:
        tmask = (tvec >= t_limits[0]) & (tvec <= t_limits[1])
        tvec = tvec[tmask]
    else:
        tmask = np.full_like(tvec, True)

    # Voltages
    V_data = {pop: [] for pop in pop_names}
    for cell, V_vec in sim_result['simData']['V_soma'].items():
        gid = int(cell.split('_')[-1])
        pop = sim_result['net']['cells'][gid]['tags']['pop']
        V_data[pop].append(np.array(V_vec)[tmask])
    for pop in pop_names:
        V_data[pop] = np.array(V_data[pop])

    return V_data, tvec '''

def get_voltages(sim_result, t_limits=None):
    pop_names = get_pop_names(sim_result)

    # full time vector + mask
    tvec = np.array(sim_result['simData']['t'])
    if t_limits is not None:
        mask = (tvec >= t_limits[0]) & (tvec <= t_limits[1])
        tvec = tvec[mask]
    else:
        mask = np.ones_like(tvec, bool)

    # 1) map gid → V_vec[mask]
    V_map = {}
    for cell_name, V_vec in sim_result['simData']['V_soma'].items():
        gid = int(cell_name.split('_')[-1])
        V_map[gid] = np.array(V_vec)[mask]

    # 2) for each pop, gather & sort gids, then stack
    V_data = {}
    pop_gids = {pop: [] for pop in pop_names}
    for gid, cell in enumerate(sim_result['net']['cells']):
        pop = cell['tags']['pop']
        pop_gids[pop].append(gid)

    for pop in pop_names:
        gids = sorted(pop_gids[pop])
        # stack into array shape (n_cells_in_pop, n_timepoints)
        V_data[pop] = np.stack([V_map[gid] for gid in gids], axis=0)

    return V_data, tvec



# =============================================================================
# def get_pop_cell_rates(sim_result, pop_name, t0=0, tmax=None):
#     S = get_pop_spikes(sim_result, pop_name, combine_cells=False)
#     if tmax is None:
#         tmax = get_sim_duration(sim_result)
#     T = tmax - t0
#     r = np.array([len(s[(s >= t0) & (s <= tmax)]) / T for s in S])
#     return r
# =============================================================================


def get_voltages_xr(
        sim_result: Dict,
        t_limits: Tuple[float, float] | None = None,
        ) -> Dict[str, xr.Dataset]:
    """Returns a dict: {pop: Vmat (cells x time)}. """

    pop_names = get_pop_names(sim_result)

    # Time bins and limits
    tvec = np.array(sim_result['simData']['t'])
    if t_limits is not None:
        tmask = (tvec >= t_limits[0]) & (tvec <= t_limits[1])
        tvec = tvec[tmask]
    else:
        tmask = np.full_like(tvec, True)

    # Extract voltages and the corresponding cell gids
    V_data = {pop: [] for pop in pop_names}
    cell_gids = {pop: [] for pop in pop_names}
    for cell, V_vec in sim_result['simData']['V_soma'].items():
        gid = int(cell.split('_')[-1])
        pop = sim_result['net']['cells'][gid]['tags']['pop']
        V_data[pop].append(np.array(V_vec)[tmask])
        cell_gids[pop].append(gid)

    # Convert to xarray
    for pop in pop_names:
        V_data[pop] = xr.DataArray(
            np.array(V_data[pop]),
            dims=['cell_gid', 'time'],
            coords={
                'cell_gid': cell_gids[pop],
                'time': tvec
            }
        )

    return V_data


def prepare_sim_result(sim) -> Dict:
    """Create sim_result from sim object, same format as in pkl. """
    
    # gather() should be called already

    if sim.rank != 0:
        return {}

    include = sim.cfg.saveDataInclude
    dataSave = {}
    net = {}
    synMechStringFuncs = None
    cellParamStringFuncs = None

    dataSave['netpyne_version'] = sim.version(show=False)
    dataSave['netpyne_changeset'] = sim.gitChangeset(show=False)

    if getattr(sim.net.params, 'version', None):
        dataSave['netParams_version'] = sim.net.params.version
    if 'netParams' in include:
        # exclude from dataSave but keep in synMechParams later, for integrity
        cellParamStringFuncs = sim.net.params.__dict__.pop('_cellParamStringFuncs', None)
        synMechStringFuncs = sim.net.params.__dict__.pop('_synMechStringFuncs', None)
        sim.net.params.__dict__.pop('_labelid', None)
        net['params'] = sim.replaceFuncObj(sim.net.params.__dict__)
    if 'net' in include:
        include.extend(['netPops', 'netCells'])
    if 'netCells' in include and hasattr(sim.net, 'allCells'):
        net['cells'] = sim.net.allCells
    if 'netPops' in include and hasattr(sim.net, 'allPops'):
        net['pops'] = sim.net.allPops
    if net:
        dataSave['net'] = net
    if 'simConfig' in include:
        dataSave['simConfig'] = sim.cfg.__dict__
    if 'simData' in include:
        if 'LFP' in sim.allSimData:
            sim.allSimData['LFP'] = sim.allSimData['LFP'].tolist()
            if hasattr(sim.net, 'recXElectrode'):
                dataSave['net']['recXElectrode'] = sim.net.recXElectrode
        dataSave['simData'] = sim.allSimData

    if synMechStringFuncs:
        sim.net.params._synMechStringFuncs = synMechStringFuncs
    if cellParamStringFuncs:
        sim.net.params._cellParamStringFuncs = cellParamStringFuncs

    return dataSave