import json
import sys

from model_tuner.sim_manager import SimBatchPaths


def post_update(cfg):
    """Called after cfg.update() """
    
    dirpath_res = cfg.saveFolder
    sim_label = cfg.sim_manager['sim_label']
    fpath_reqs = cfg.sim_manager['requests_file']

    print(f'Job script started (label={sim_label})', flush=True)
    print(f'File with sim requests: {fpath_reqs}', flush=True)
    print(f'Output folder for the results: {dirpath_res}', flush=True)

    # Set the sim label that was passed from SimManager
    cfg.simLabel = sim_label

    # Read the request generated by SimManager
    with open(fpath_reqs, 'r') as fid:
        sim_request = json.load(fid)[sim_label]

    print('Request:')
    print(sim_request)

    # Get cfg fields from the request
    if 'input' in sim_request:
        cfg.ou_pop_inputs = sim_request['input']
    if 'connected' in sim_request:
        cfg.addConn = sim_request['connected']
    if 'wmult' in sim_request:
        cfg.wmult = sim_request['wmult']
    if 'subnet_params' in sim_request:
        cfg.subnet_params |= sim_request['subnet_params']
    if 'duration' in sim_request:
        cfg.duration = sim_request['duration']
